({
    name: "main",
    baseUrl: 'app',
    mainConfigFile: 'app/main.js',
    include: [
		'jquery',
		'text',
		'Q',
		'knockout',

        '_components/bindingHandlers/backgroundBindingHandler',
        '_components/bindingHandlers/overlayBindingHandler',
        '_components/bindingHandlers/progressbarBindingHandler',
        '_components/bindingHandlers/readystatechangeBindingHandler',
        '_components/bindingHandlers/scrollElementBindingHandler',
        '_components/bindingHandlers/thumbnailBindingHandler',

        'entities/course',
        'entities/DragAndDrop',
        'entities/FillInTheBlanks',
        'entities/Multipleselect',
        'entities/Objective',
        'entities/Singleselect',
        'entities/SingleselectImage',
        'entities/TextMatching',
        'entities/Hotspot',

        'introduction/viewmodels/index',
        'text!introduction/views/index.html',

        'preassessment/viewmodels/index',
        'text!preassessment/views/index.html',


        'studying/viewmodels/index',
		'studying/viewmodels/readings',
		'studying/viewmodels/studyadvice',
        'text!studying/views/index.html',
		'text!studying/views/readings.html',
        'text!studying/views/studyadvice.html',

        'summary/viewmodels/index',
        'text!summary/views/index.html',

        'viewmodels/bindingHandlers/DragAndDrop',
        'viewmodels/bindingHandlers/FillInTheBlanks',
        'viewmodels/bindingHandlers/TextMatching',
        'viewmodels/bindingHandlers/Hotspot',

        'viewmodels/404',

        'viewmodels/DragAndDrop',
        'viewmodels/factory',
        'viewmodels/FillInTheBlanks',
        'viewmodels/Multipleselect',
        'viewmodels/notSupportedBrowser',
        'viewmodels/notSupportedMobileBrowser',
        'viewmodels/Question',
        'viewmodels/shell',
        'viewmodels/Singleselect',
        'viewmodels/SingleselectImage',
        'viewmodels/TextMatching',
        'viewmodels/Hotspot',

        'views/helpers/FillInTheBlanks',
        'views/helpers/TextMatching',
        'text!views/404.html',
        'text!views/DragAndDrop.html',
        'text!views/FillInTheBlanks.html',
        'text!views/Multipleselect.html',
        'text!views/notSupportedBrowser.html',
        'text!views/notSupportedMobileBrowser.html',
        'text!views/shell.html',
        'text!views/Singleselect.html',
        'text!views/SingleselectImage.html',
        'text!views/TextMatching.html',
        'text!views/Hotspot.html',

        'xApi/configuration/settings',
        'xApi/entities/activity',
        'xApi/entities/activityDefinition',
		'xApi/entities/actor',
        'xApi/entities/context',
        'xApi/entities/contextActivities',
        'xApi/entities/object',
        'xApi/entities/result',
        'xApi/entities/score',
        'xApi/entities/statement',
        'xApi/entities/verb',
        'text!xApi/errorHandling/errorDialog.html',
		'xApi/errorHandling/errorDialog',
        'xApi/errorHandling/errorHandler',
        'xApi/requestsTransport/corsRequestTransport',
		'xApi/requestsTransport/requestSender',
        'xApi/requestsTransport/xDomainRequestTransport',
        'xApi/utils/base64',
        'xApi/utils/dateTimeConverter',
        'xApi/viewmodels/login',
        'text!xApi/views/login.html',
        'xApi/activityProvider',
        'xApi/guard',
        'xApi/initializer',
        'xApi/statementsQueue',
        'xApi/statementsQueueHandler',
        'xApi/verbs',


		'bootstrapper',
		'browserDetector',
		'controller',
		'courseSettingsModule',
		'dataContext',
		'eventManager',
		'loader',
		'modulesInitializer',
        'publishSettingsModule'
    ]
})